FROM python:3-alpine

COPY ./requirements.txt /tmp/requirements.txt
COPY ./monitor.sh /monitor.sh

RUN pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt && \
    rm -rf /tmp && \
    chmod +x /monitor.sh && \
    echo "*/5 * * * * /monitor.sh" >> /var/spool/cron/crontabs/root

CMD crond -f -l 2 -L /dev/stdout